language: python
python:
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: pip

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -U postgres -c 'CREATE DATABASE jorvik;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d jorvik
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d jorvik

  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux32.zip -O /tmp/chromedriver.zip
  - unzip /tmp/chromedriver.zip -d /tmp
  - mkdir -p /tmp/cdriver/
  - mv /tmp/chromedriver /tmp/cdriver/chromedriver
  - export PATH=$PATH:/tmp/cdriver/

install:
  - "pip install -U pip wheel"
  - "pip install -r requirements.txt"


script:
  - "python ./manage.py test -v 3"
