language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"


#before_script:
#  - "mysql -e 'CREATE DATABASE jorvik CHARSET utf8;'"
before_script:
  - psql -U postgres -c 'CREATE DATABASE jorvik;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d jorvik
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d jorvik

install:
  - "pip install -r requirements.txt"

script:
  - "python ./manage.py migrate"
  - "python ./manage.py test -d -v 3"
