language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"

cache: pip

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -U postgres -c 'CREATE DATABASE jorvik;'
  - psql -U postgres -c "CREATE EXTENSION postgis" -d jorvik
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d jorvik

install:
  - "pip install -U pip wheel"
  - "pip install -r requirements.txt"


script:
  # Inserisce la chiave API da variabile GOOGLE_KEY in config/apis.cnf
  #  questa e' usata per i test della locazione.
  - 'echo "[google]\n\napi_key = $GOOGLE_KEY\n" > ./config/apis.cnf'
  - "python ./manage.py test -v 3 --parallel 2"
