language: python
python:
  - "3.3"
  - "3.4"

before_script:
  - mysql -e 'create database jorvik_test;'

install:
  - "pip install -r requirements.txt"

script:
  - "python ./manage.py migrate"
  - "python ./manage.py test"
